// turbo5 KV quantization -- the 5-bit K rung. q27-original (turbo3 is a port
// of Gabe's llama.cpp TurboQuant fork; there is no 5-bit upstream to match).
//
// WHY THIS EXISTS. The 2026-08-01 KV tail study measured every format against
// an fp16 reference and found turbo3 carries 6.0x fp8's catastrophic-position
// count at a dPPL of only +0.804% -- PPL is blind on that axis. Spending bits
// on K is the right direction (turbo3v, fp16 K + turbo3 V, cuts catastrophic
// 114 -> 52) but fp16 K is a sledgehammer: K is half the cache, so turbo3v
// lands at 41.0 KB/tok, BIGGER than fp8's 34.0 and worse on every metric.
// q27 jumped 3-bit -> fp8 with nothing between, and every best-value config in
// anbeeld's KV benchmarks lives in the 5-6 bit band we skipped. turbo5k =
// 5-bit K + 3-bit V fills it at ~18.6 KB/tok. Plan: docs/plans/2026-08-01-5bit-k.md.
//
// WHAT CHANGES vs turbo3: the centroid table and the bit packing, nothing else.
// The WHT rotation (TURBO_S1/S2, turbo3_butterfly128), the per-block L2 norm,
// the recon-norm correction, and the fp16 norm field are reused VERBATIM from
// turbo3.cuh -- this header includes it rather than restating any of it, so
// the two formats cannot drift on the shared half. The correctness contract is
// therefore identical: dequant(K) == WHT(K), so the attention dot computes
// WHT(q).dequant(K) == q.K (WHT is orthonormal) and the pooled output is
// WHT(true output), un-rotated by the engine's single inverse WHT. That is
// what lets a turbo5 K and a turbo3 V share one rotation.
//
// q27 mapping (head_dim=256 = TWO 128-groups, no padding):
//   block_turbo5 = 82 bytes covering 128 dims; 2 blocks per (kv_head).
// The microtest (tools/turbo5_test.cu) validates this header against a CPU
// oracle bit-for-bit before any engine wiring.
#pragma once
#include "turbo3.cuh" // shared: WHT diagonals, butterfly128, block/norm idiom

namespace q27turbo {

static constexpr int QK_TURBO5 = 128; // elements per block == WHT group

// 82-byte block: fp16 norm + 4-bit indices (qs, 2 per byte) + 1 high bit (hi,
// 8 per byte). The split is chosen so the fd2 lane layout maps on with zero
// reshuffle: lane l owns dims 4l..4l+3, which is exactly qs[2l..2l+1] plus
// nibble (l&1)*4 of hi[l>>1] -- the same hi-byte addressing turbo3's signs use.
// 82 is even and cudaMalloc bases are 256B-aligned, so every qs/hi offset is
// 2-byte aligned and the lane's 2 qs bytes are one aligned ushort.
struct block_turbo5 {
    __half  norm;                 // corrected L2 norm (grp_norm / recon_norm)
    uint8_t qs[QK_TURBO5 / 2];    // 64 B: low 4 bits, 2 per byte
    uint8_t hi[QK_TURBO5 / 8];    // 16 B: high bit, 8 per byte
};
static_assert(sizeof(block_turbo5) == sizeof(__half) + QK_TURBO5/2 + QK_TURBO5/8,
              "turbo5 block must be 82 bytes, no padding");

// 32 Lloyd-Max centroids for a unit-norm coordinate, derived the same way
// turbo3's 8 were: the optimal 32-level Lloyd-Max quantizer for N(0,1), scaled
// by 1/sqrt(128) (a WHT-rotated unit-L2 128-vector has ~N(0, 1/128) coords).
// Generated by scratchpad/lloydmax.py, whose 8-level output reproduces
// turbo3's SHIPPED table to 4.7e-7 -- that agreement is the derivation's own
// gate. Distortion D = 0.00250467 (SNR 26.01 dB) vs 3-bit's 0.034548 (14.62
// dB), predicting a round-trip cosine of 0.998747 vs turbo3's 0.983.
//
// THRESH = the 31 decision boundaries, exact midpoints of the float32
// centroids (for a Lloyd-Max quantizer the optimal boundary IS the midpoint).
// The _LIST macros keep the device __constant__ arrays and the host mirrors
// literally the same token sequence -- no re-typed copies. turbo3's phase-1
// "4096 mismatches" was a hand-transcription bug in exactly such a copy, and
// a 32-entry table is four times the surface for it.
#define Q27_TURBO5_CENTROIDS_LIST { \
    -0.28821075f, -0.23786362f, -0.20486116f, -0.17931595f, \
    -0.15797059f, -0.13932019f, -0.12253633f, -0.10710939f, \
    -0.09270022f, -0.07906913f, -0.06603809f, -0.05346908f, \
    -0.04125080f, -0.02928998f, -0.01750547f, -0.00582388f, \
     0.00582388f,  0.01750547f,  0.02928998f,  0.04125080f, \
     0.05346908f,  0.06603809f,  0.07906913f,  0.09270022f, \
     0.10710939f,  0.12253633f,  0.13932019f,  0.15797059f, \
     0.17931595f,  0.20486116f,  0.23786362f,  0.28821075f }
#define Q27_TURBO5_THRESH_LIST { \
    -0.26303717f, -0.22136238f, -0.19208856f, -0.16864327f, \
    -0.14864540f, -0.13092826f, -0.11482286f, -0.09990481f, \
    -0.08588468f, -0.07255360f, -0.05975358f, -0.04735994f, \
    -0.03527039f, -0.02339773f, -0.01166468f,  0.00000000f, \
     0.01166468f,  0.02339773f,  0.03527039f,  0.04735994f, \
     0.05975358f,  0.07255360f,  0.08588468f,  0.09990481f, \
     0.11482286f,  0.13092826f,  0.14864540f,  0.16864327f, \
     0.19208856f,  0.22136238f,  0.26303717f }

#ifdef __CUDACC__
__device__ __constant__ static float TURBO_CENTROIDS_5BIT[32] = Q27_TURBO5_CENTROIDS_LIST;
__device__ __constant__ static float TURBO_THRESH_5BIT[31] = Q27_TURBO5_THRESH_LIST;
#endif
[[maybe_unused]] static const float TURBO_CENTROIDS_5BIT_HOST[32] = Q27_TURBO5_CENTROIDS_LIST;
[[maybe_unused]] static const float TURBO_THRESH_5BIT_HOST[31] = Q27_TURBO5_THRESH_LIST;

// nearest-centroid index. turbo3's 8-level if-chain would be 31 branches here,
// so this counts thresholds instead: idx = #{i : v >= T[i]}, which is exactly
// what turbo3_nearest's "first i with v < T[i]" chain returns. Fully unrolled,
// so every T[i] is a compile-time __constant__ address (uniform broadcast, not
// a divergent gather) and the whole thing is branch-free -- fixed order, so
// host and device agree bit-for-bit. Both sides read the SAME macro.
__host__ __device__ __forceinline__ int turbo5_nearest(float v) {
#if defined(__CUDA_ARCH__)
    const float* T = TURBO_THRESH_5BIT;
#else
    const float* T = TURBO_THRESH_5BIT_HOST;
#endif
    int idx = 0;
#if defined(__CUDA_ARCH__)
#pragma unroll
#endif
    for (int i = 0; i < 31; i++) idx += (v >= T[i]);
    return idx;
}

#ifdef __CUDACC__
// One dequanted element from a block (idx = low4 | hi1<<4) * norm.
__device__ __forceinline__ float turbo5_dequant(const block_turbo5* b, int j, float norm) {
    uint8_t low4 = (b->qs[j >> 1] >> ((j & 1) * 4)) & 0xF;
    uint8_t hi1  = (b->hi[j >> 3] >> (j & 7)) & 0x1;
    return TURBO_CENTROIDS_5BIT[low4 | (hi1 << 4)] * norm;
}

// Cooperative 128-group quantize: one CUDA block of 128 threads = one group,
// thread j owns element x = src[j]. Structurally identical to
// turbo3_quant_group -- fixed-order L2 reduce -> s1/butterfly/s2 forward WHT
// (the SHARED rotation) -> nearest-centroid pack -> corrected fp16 norm -- and
// like it, shared by the decode store (spec3.cu) and the prefill store
// (prefill.cu) so the two writers cannot drift. All reductions and the
// butterfly are fixed-order => run-to-run deterministic. xs/red are
// caller-provided smem[128].
//
// Packing differs from turbo3 only in width: the low 4 bits pair across
// adjacent threads (one shfl_down instead of three), and the 5th bit uses the
// same ballot the 3rd bit did.
__device__ __forceinline__ void turbo5_quant_group(float x, block_turbo5* dst, int j,
                                                   float* xs, float* red) {
    xs[j] = x;
    red[j] = x * x;
    __syncthreads();
#pragma unroll
    for (int s = 64; s > 0; s >>= 1) {
        if (j < s) red[j] += red[j + s];
        __syncthreads();
    }
    float gn = sqrtf(red[0]);
    float inv = gn > 1e-10f ? 1.f / gn : 0.f;
    xs[j] = xs[j] * inv * TURBO_S1[j];
    turbo3_butterfly128(xs, j);
    float w = xs[j] * (TURBO_INV_SQRT_128 * TURBO_S2[j]);
    int idx = turbo5_nearest(w);
    red[j] = TURBO_CENTROIDS_5BIT[idx] * TURBO_CENTROIDS_5BIT[idx];
    __syncthreads();
#pragma unroll
    for (int s = 64; s > 0; s >>= 1) {
        if (j < s) red[j] += red[j + s];
        __syncthreads();
    }
    float rn = sqrtf(red[0]);
    float corr = rn > 1e-10f ? gn / rn : gn;
    int low4 = idx & 15;
    unsigned bal = __ballot_sync(0xffffffffu, idx & 16);
    int l1 = __shfl_down_sync(0xffffffffu, low4, 1);
    if ((j & 1) == 0) dst->qs[j >> 1] = (uint8_t)(low4 | (l1 << 4));
    if ((j & 7) == 0) dst->hi[j >> 3] = (uint8_t)((bal >> (j & 31)) & 0xFF);
    if (j == 0) dst->norm = __float2half(corr);
}

// One dequanted element d (0..255) from a 2-block row (head_dim 256).
__device__ __forceinline__ float turbo5_deq_elem(const block_turbo5* row2, int d) {
    const block_turbo5* b = row2 + (d >> 7);
    return turbo5_dequant(b, d & 127, __half2float(b->norm));
}

// fd2 lane load: lane l owns dims {4l..4l+3} of block b2[0] and {128+4l..}
// of b2[1] -- the fd2 lane layout still maps 1:1 onto the two 128-groups with
// zero reshuffle at 5 bits, but the byte arithmetic is NOT turbo3's: the four
// dims are one aligned ushort of qs (2 nibbles per byte) instead of one qs
// byte, while the 5th bit reuses turbo3's exact signs addressing (hi[l>>1],
// bits (l&1)*4+i). Because that is the one place the wider packing could go
// wrong, it lives HERE -- shared by the fd2 kernel and gated directly by the
// microtest -- rather than being retyped inside spec3.cu the way turbo3's is.
__device__ __forceinline__ void turbo5_ld8_lane(const block_turbo5* __restrict__ b2,
                                                int lane, float* o) {
#pragma unroll
    for (int g = 0; g < 2; g++) {
        const block_turbo5* b = b2 + g;
        float norm = __half2float(b->norm);
        uint16_t q2 = *reinterpret_cast<const uint16_t*>(b->qs + 2 * lane);
        uint8_t h = b->hi[lane >> 1];
        int sh = (lane & 1) * 4;
#pragma unroll
        for (int i = 0; i < 4; i++) {
            int idx = ((q2 >> (4 * i)) & 0xF) | (((h >> (sh + i)) & 1) << 4);
            o[4 * g + i] = TURBO_CENTROIDS_5BIT[idx] * norm;
        }
    }
}

// Stage 8 consecutive dims (d8 8-aligned, 0..248) from a 2-block row into
// 4 half2 (the mma prefill smem-tile layout): 4 qs bytes + 1 hi byte + 1 norm
// per call. Mirrors turbo3_stage8_h2's read pattern at 5 bits.
__device__ __forceinline__ void turbo5_stage8_h2(const block_turbo5* row2, int d8,
                                                 __half2* dst) {
    const block_turbo5* b = row2 + (d8 >> 7);
    int j0 = d8 & 127;
    float norm = __half2float(b->norm);
    const uint8_t* q = b->qs + (j0 >> 1); // 4 bytes cover the 8 dims
    uint8_t h8 = b->hi[j0 >> 3];
    float v[8];
#pragma unroll
    for (int i = 0; i < 4; i++) {
        int lo = (q[i] & 0xF) | (((h8 >> (2 * i)) & 1) << 4);
        int hi = ((q[i] >> 4) & 0xF) | (((h8 >> (2 * i + 1)) & 1) << 4);
        v[2 * i] = TURBO_CENTROIDS_5BIT[lo] * norm;
        v[2 * i + 1] = TURBO_CENTROIDS_5BIT[hi] * norm;
    }
#pragma unroll
    for (int j = 0; j < 4; j++)
        dst[j] = __halves2half2(__float2half_rn(v[2 * j]), __float2half_rn(v[2 * j + 1]));
}

// Same 8-dim stage as e4m3 bytes (the fdmma verify tiles): the MMA operands
// become e4m3(centroid*norm) -- one extra rounding on top of the 5-bit quant,
// same tolerance class as fdmma's own e4m3 Q/P staging and as turbo3's
// equivalent. Mirrors turbo3_stage8_e4m3 exactly; only the unpack differs.
__device__ __forceinline__ void turbo5_stage8_e4m3(const block_turbo5* row2, int d8,
                                                   __nv_fp8_e4m3* dst) {
    const block_turbo5* b = row2 + (d8 >> 7);
    int j0 = d8 & 127;
    float norm = __half2float(b->norm);
    const uint8_t* q = b->qs + (j0 >> 1);
    uint8_t h8 = b->hi[j0 >> 3];
#pragma unroll
    for (int i = 0; i < 4; i++) {
        int lo = (q[i] & 0xF) | (((h8 >> (2 * i)) & 1) << 4);
        int hi = ((q[i] >> 4) & 0xF) | (((h8 >> (2 * i + 1)) & 1) << 4);
        dst[2 * i] = __nv_fp8_e4m3(TURBO_CENTROIDS_5BIT[lo] * norm);
        dst[2 * i + 1] = __nv_fp8_e4m3(TURBO_CENTROIDS_5BIT[hi] * norm);
    }
}
#endif

} // namespace q27turbo
